# Generated by Django 2.2 on 2021-05-22 04:50

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210521_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books_written',
        ),
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(default='  ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='phone_no',
            field=models.CharField(blank=True, default='99******75', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='management.Author'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(default=datetime.datetime(2021, 5, 22, 4, 50, 40, 600861, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
